### ISSUE TITLE
Implement iRods Connection Pooling

### ISSUE THREAD

**Issue by jjacquay712** [jjacquay712/GoRods#20]
Proposed syntax:

```go
gorods.connpool.New(int connExpire, int maxConn) // create connection pool, specify timeout (s) for connections, maximum connections (calls Expire() first and then closes oldest connection when none were expired on each Open() after maxxConn is reached)
gorods.connpool.Expire() // close/disconnect all expired connections
gorods.connpool.Open(string userName, etc... ) // calls gorods.New() for a given iRODS user and registers them in the pool, timestamped for expiration, etc.
gorods.connpool.Close(string userName) // explicit close/disconect of a connection (from logout, etc.) from the pool
gorods.connpool.Get(string userName) // returns the GoRods connection for the username
```

**Comment by jjacquay712** [comment]
After some investigation, I've found that using a single GoRods connection within multiple Goroutines (from net/http server) causes low-level network library errors. This issue could be remedied with connection pooling, transparent to the implementer of GoRods:

- gorods.New is called with credentails / server configuration, a single connection is tested, then added to the pool if successful
- Every GoRods function call looks for an unlocked connection to use, if all connections are in use, another is spun up
- If an existing connection is available, it uses that connection and "locks" it
- The connection pool has two configuration options: max_connections, idle_pool_size

**Comment by jacquayj** [comment]
I've found that data object and collection handles must be used only with the same connection they were created with, so that makes the idea of connection pools difficult to implement and not very worth while. The iRODS authors also state "The view I take is that iRODS has grown over time based on the 'icommand' model, where a command connects, does its job, and then disconnects.  Especially if your client is widely distributed, my own best practice is to avoid holding on to idle connections.  There can also be dangers of dropping connections that are idle if you are overly reliant on continuously held connections.".
